/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "3.2_Release_dev_20240321-h0.EMUI.HarmonyOS.hmos_trunk.r10-5-g6ea9fc09c7"
#endif /* AVUTIL_FFVERSION_H */
